title: HADA MADRINA
description: Results of the research project Human Aware Data science for MAchine learning DRIveN Applications
theme: just-the-docs

url: https://emipar.github.io/hada-madrina

aux_links:
  Template Repository: #https://github.com/just-the-docs/just-the-docs-template
